/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dairymanagement;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aswin
 */
public class Purchases extends javax.swing.JFrame {

    /**
     * Creates new form Purchases
     */
    public Purchases() {
        initComponents();
        fetch();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Home2 = new javax.swing.JLabel();
        Add1 = new javax.swing.JLabel();
        Update1 = new javax.swing.JLabel();
        Delete1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        type1 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        Quantity1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Rate1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Date1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        PurchaseTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setBackground(new java.awt.Color(254, 254, 254));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/LOGOUT (1).png"))); // NOI18N
        Logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 20, 150, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Purchase (3).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 100));

        jPanel4.setBackground(new java.awt.Color(62, 68, 71));

        Home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home.png"))); // NOI18N
        Home2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home2MouseClicked(evt);
            }
        });

        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/insert.png"))); // NOI18N
        Add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add1MouseClicked(evt);
            }
        });

        Update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/update.png"))); // NOI18N
        Update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update1MouseClicked(evt);
            }
        });

        Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/delete.png"))); // NOI18N
        Delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Update1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Home2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Home2)
                .addGap(18, 18, 18)
                .addComponent(Add1)
                .addGap(18, 18, 18)
                .addComponent(Update1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 80, 668));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/sell.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Product.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Quantity.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Rate.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Date.png"))); // NOI18N

        SName.setBackground(new java.awt.Color(254, 254, 254));
        SName.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        SName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        type1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        type1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milk : Cow", "Milk : Goat", "Milk : Buffalo", "Butter", "Ghee", "Cheese", "Cream", "Select the Product" }));
        type1.setSelectedIndex(7);

        Quantity1.setBackground(new java.awt.Color(254, 254, 254));
        Quantity1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Quantity1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Rate1.setBackground(new java.awt.Color(254, 254, 254));
        Rate1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Rate1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Date1.setBackground(new java.awt.Color(254, 254, 254));
        Date1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Date1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText(" Note : Use format DD/MM/YYYY for date");

        PurchaseTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PurchaseTable.setFont(new java.awt.Font("Ubuntu Light", 0, 22)); // NOI18N
        PurchaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seller Id", "Seller Name", "Product", "Quantity", "Rate", "Amount", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        PurchaseTable.setName(""); // NOI18N
        PurchaseTable.setRowHeight(24);
        PurchaseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PurchaseTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PurchaseTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rate1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SName, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rate1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 1360, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Login log1=new Login();
        log1.show();
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void Home2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home2MouseClicked
        // TODO add your handling code here:
        Dashboard dash=new Dashboard();
        dash.show();
        dispose();
    }//GEN-LAST:event_Home2MouseClicked

    private void Add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add1MouseClicked
        if(type1.getSelectedItem()=="Select the Product" || SName.getText().isEmpty() || Quantity1.getText().isEmpty() || Rate1.getText().isEmpty() || Date1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Select and fill all the fields");
        }
        else{
            String SellerName=SName.getText();
            String MilkType=(String) type1.getSelectedItem();
            int Quantity=Integer.parseInt(Quantity1.getText());
            int Rate=Integer.parseInt(Rate1.getText());
            int Amount=Rate*Quantity;
            String Date=Date1.getText();
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Dairymanagement","root","");
                Statement stmt = con.createStatement();
                String sql1="SELECT * FROM Purchases WHERE SellerName='"+SellerName+"' AND MilkType='"+MilkType+"' AND Quantity='"+Quantity+"' AND Rate='"+Rate+"' AND Amount='"+Amount+"' AND Date='"+Date+"' ";
                ResultSet rs1 = stmt.executeQuery(sql1);
                if(rs1.next())
                {
                    JOptionPane.showMessageDialog(null, "Entry Already Exists");
                    clear();
                }
                else
                {
                    String sql="INSERT INTO Purchases(SellerName,MilkType,Quantity,Rate,Amount,Date)VALUES('"+SellerName+"','"+MilkType+"','"+Quantity+"','"+Rate+"','"+Amount+"','"+Date+"');";
                    Statement st=con.createStatement();
                    int rs=st.executeUpdate(sql);
                    if(rs==1){
                        JOptionPane.showMessageDialog(this,"Data Added");
                        fetch();
                        clear();
                    }
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_Add1MouseClicked

    private void Update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update1MouseClicked
        // TODO add your handling code here:
        if(type1.getSelectedItem()=="Select the Product" || SName.getText().isEmpty() || Quantity1.getText().isEmpty() || Rate1.getText().isEmpty() || Date1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Select and fill all the fields");
        }
        else{
            try{
                DefaultTableModel d1=(DefaultTableModel)PurchaseTable.getModel();
                int index=Integer.parseInt(d1.getValueAt(PurchaseTable.getSelectedRow(),0).toString());
                String SellerName=SName.getText();
                String MilkType=(String) type1.getSelectedItem();
                int Quantity=Integer.parseInt(Quantity1.getText());
                int Rate=Integer.parseInt(Rate1.getText());
                int Amount=Rate*Quantity;
                String Date=Date1.getText();
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Dairymanagement","root","");
                String sql="update Purchases set SellerName='"+SellerName+"',MilkType='"+MilkType+"',Quantity='"+Quantity+"',Rate='"+Rate+"',Amount='"+Amount+"',Date='"+Date+"' where Id='"+index+"'";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.executeUpdate(sql);
                fetch();
                clear();
                JOptionPane.showMessageDialog(null, "Updated");
            }
            catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_Update1MouseClicked

    private void Delete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete1MouseClicked
        // TODO add your handling code here:
        try{
            DefaultTableModel d1=(DefaultTableModel)PurchaseTable.getModel();
            int index=Integer.parseInt(d1.getValueAt(PurchaseTable.getSelectedRow(),0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Dairymanagement","root","");
            String sql="DELETE FROM Purchases WHERE Id='"+index+"'";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.executeUpdate(sql);
            fetch();
            clear();
            JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Delete1MouseClicked

    private void PurchaseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchaseTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1=(DefaultTableModel)PurchaseTable.getModel();
        int index=PurchaseTable.getSelectedRow();
        SName.setText(d1.getValueAt(index, 1).toString());
        if(d1.getValueAt(index,2).toString().equals("Milk : Cow")){
            type1.setSelectedIndex(0);
        }
        else if(d1.getValueAt(index,2).toString().equals("Milk : Goat")){
            type1.setSelectedIndex(1);
        }
        else if(d1.getValueAt(index,2).toString().equals("Milk : Buffalo")){
            type1.setSelectedIndex(2);
        }
        else if(d1.getValueAt(index,2).toString().equals("Butter")){
            type1.setSelectedIndex(3);
        }
        else if(d1.getValueAt(index,2).toString().equals("Ghee")){
            type1.setSelectedIndex(4);
        }
        else if(d1.getValueAt(index,2).toString().equals("Cheese")){
            type1.setSelectedIndex(5);
        }
        else{
            type1.setSelectedIndex(6);
        }
        Quantity1.setText(d1.getValueAt(index, 3).toString());
        Rate1.setText(d1.getValueAt(index, 4).toString());
        Date1.setText(d1.getValueAt(index, 6).toString());
    }//GEN-LAST:event_PurchaseTableMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add1;
    private javax.swing.JTextField Date1;
    private javax.swing.JLabel Delete1;
    private javax.swing.JLabel Home2;
    private javax.swing.JButton Logout;
    private javax.swing.JTable PurchaseTable;
    private javax.swing.JTextField Quantity1;
    private javax.swing.JTextField Rate1;
    private javax.swing.JTextField SName;
    private javax.swing.JLabel Update1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> type1;
    // End of variables declaration//GEN-END:variables

    private void fetch() {
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Dairymanagement","root","");
           String sql="select * from Purchases";
           Statement stmt=con.createStatement();
           ResultSet rs=stmt.executeQuery(sql);
           DefaultTableModel d1=(DefaultTableModel)PurchaseTable.getModel();
           d1.setRowCount(0);
           while(rs.next())
           {
               
               Vector v2=new Vector();
                    v2.add(rs.getString("Id"));
                    v2.add(rs.getString("SellerName"));
                    v2.add(rs.getString("MilkType"));
                    v2.add(rs.getString("Quantity"));
                    v2.add(rs.getString("Rate"));
                    v2.add(rs.getString("Amount"));
                    v2.add(rs.getString("Date"));
               d1.addRow(v2);
           }
       }
       catch(Exception e)
       {
           System.out.println(e);
       }
    }

    private void clear() {

       
        SName.setText("");
        type1.setSelectedIndex(7);
        Quantity1.setText("");
        Rate1.setText("");
        Date1.setText("");
    }
}
