/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dairymanagement;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aswin
 */
public class Staffs extends javax.swing.JFrame {

    /**
     * Creates new form Staffs
     */
    public Staffs() {
        initComponents();
        fetch();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Logout1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Home3 = new javax.swing.JLabel();
        Add1 = new javax.swing.JLabel();
        Update1 = new javax.swing.JLabel();
        Delete1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        StName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        PhnNum1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        StAdd = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Age = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Others = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StaffsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout1.setBackground(new java.awt.Color(254, 254, 254));
        Logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/LOGOUT (1).png"))); // NOI18N
        Logout1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });
        jPanel1.add(Logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 20, 150, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/staff.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 100));

        jPanel4.setBackground(new java.awt.Color(62, 68, 71));

        Home3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home.png"))); // NOI18N
        Home3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home3MouseClicked(evt);
            }
        });

        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/insert.png"))); // NOI18N
        Add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add1MouseClicked(evt);
            }
        });

        Update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/update.png"))); // NOI18N
        Update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update1MouseClicked(evt);
            }
        });

        Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/delete.png"))); // NOI18N
        Delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Update1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Home3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Home3)
                .addGap(18, 18, 18)
                .addComponent(Add1)
                .addGap(18, 18, 18)
                .addComponent(Update1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 80, 668));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/name.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/phn.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/addr.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/age.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gen.png"))); // NOI18N

        StName.setBackground(new java.awt.Color(254, 254, 254));
        StName.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        StName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        PhnNum1.setBackground(new java.awt.Color(254, 254, 254));
        PhnNum1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        PhnNum1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        StAdd.setBackground(new java.awt.Color(254, 254, 254));
        StAdd.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        StAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Age.setBackground(new java.awt.Color(254, 254, 254));
        Age.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Age.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Gender.add(Male);
        Male.setFont(new java.awt.Font("FreeSans", 0, 22)); // NOI18N
        Male.setForeground(new java.awt.Color(1, 1, 1));
        Male.setText("Male");

        Gender.add(Female);
        Female.setFont(new java.awt.Font("FreeSans", 0, 22)); // NOI18N
        Female.setForeground(new java.awt.Color(1, 1, 1));
        Female.setText("Female");

        Gender.add(Others);
        Others.setFont(new java.awt.Font("FreeSans", 0, 22)); // NOI18N
        Others.setForeground(new java.awt.Color(1, 1, 1));
        Others.setText("Others");

        StaffsTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        StaffsTable.setFont(new java.awt.Font("Ubuntu Light", 0, 22)); // NOI18N
        StaffsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff Id", "Name", "Phone Number", "Address", "Age", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        StaffsTable.setRowHeight(24);
        StaffsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StaffsTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator5)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(StName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PhnNum1)
                            .addComponent(jSeparator3)
                            .addComponent(StAdd)
                            .addComponent(jSeparator4)
                            .addComponent(Age)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Male)
                        .addGap(18, 18, 18)
                        .addComponent(Female)
                        .addGap(18, 18, 18)
                        .addComponent(Others)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Male)
                            .addComponent(Female)
                            .addComponent(Others))
                        .addGap(0, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 1360, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Home3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home3MouseClicked
        // TODO add your handling code here:
        Dashboard dash=new Dashboard();
        dash.show();
        dispose();
    }//GEN-LAST:event_Home3MouseClicked

    private void Add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add1MouseClicked
        if(StName.getText().isEmpty() || PhnNum1.getText().isEmpty() || StAdd.getText().isEmpty() || Age.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Select and fill all the fields");
        }
        else{
            String Name=StName.getText();
            String PhnNum=PhnNum1.getText();
            String Address=StAdd.getText();
            int Age1=Integer.parseInt(Age.getText());
            String gender;
            if(Male.isSelected()){
                gender="Male";
            }
            else if(Female.isSelected()){
                gender="Female";
            }
            else{
                gender="Others";
            }
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Dairymanagement","root","");
                Statement stmt = con.createStatement();
                String sql1="SELECT * FROM Staffs WHERE Name='"+Name+"' AND PhoneNumber='"+PhnNum+"' AND Address='"+Address+"' AND Age='"+Age1+"' AND Gender='"+gender+"'";
                ResultSet rs1 = stmt.executeQuery(sql1);
                if(rs1.next())
                {
                    JOptionPane.showMessageDialog(null, "Entry Already Exists");
                    clear();
                }
                else
                {
                    String sql="INSERT INTO Staffs(Name,PhoneNumber,Address,Age,Gender)VALUES('"+Name+"','"+PhnNum+"','"+Address+"','"+Age1+"','"+gender+"');";
                    Statement st=con.createStatement();
                    int rs=st.executeUpdate(sql);
                    if(rs==1){
                        JOptionPane.showMessageDialog(this,"Data Added");
                        fetch();
                        clear();
                    }
                }

            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_Add1MouseClicked

    private void Update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update1MouseClicked
        // TODO add your handling code here:
        if(StName.getText().isEmpty() || PhnNum1.getText().isEmpty() || StAdd.getText().isEmpty() || Age.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Select and fill all the fields");
        }
        else{
            try{
                DefaultTableModel d1=(DefaultTableModel)StaffsTable.getModel();
                int index=Integer.parseInt(d1.getValueAt(StaffsTable.getSelectedRow(),0).toString());
                String Name=StName.getText();
                String PhnNum=PhnNum1.getText();
                String Address=StAdd.getText();
                int Age1=Integer.parseInt(Age.getText());
                String gender;
                if(Male.isSelected()){
                    gender="Male";
                }
                else if(Female.isSelected()){
                    gender="Female";
                }
                else{
                    gender="Others";
                }
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Dairymanagement","root","");
                String sql="update Staffs set Name='"+Name+"',PhoneNumber='"+PhnNum+"',Address='"+Address+"',Age='"+Age1+"',Gender='"+gender+"' where Id='"+index+"'";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.executeUpdate(sql);
                fetch();
                clear();
                JOptionPane.showMessageDialog(null, "Updated");
            }
            catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_Update1MouseClicked

    private void Delete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete1MouseClicked
        // TODO add your handling code here:
       try{
            DefaultTableModel d1=(DefaultTableModel)StaffsTable.getModel();
            int index=Integer.parseInt(d1.getValueAt(StaffsTable.getSelectedRow(),0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Dairymanagement","root","");
            String sql="DELETE FROM Staffs WHERE Id='"+index+"'";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.executeUpdate(sql);
            fetch();
            clear();
            JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Delete1MouseClicked

    private void StaffsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffsTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1=(DefaultTableModel)StaffsTable.getModel();
        int index=StaffsTable.getSelectedRow();
        StName.setText(d1.getValueAt(index, 1).toString());
        PhnNum1.setText(d1.getValueAt(index, 2).toString());
        StAdd.setText(d1.getValueAt(index, 3).toString());
        Age.setText(d1.getValueAt(index, 4).toString());
        if(d1.getValueAt(index,5).toString().equals("Male")){
            Male.setSelected(true);
        }else if(d1.getValueAt(index,5).toString().equals("Female")){
            Female.setSelected(true);
        }else{
            Others.setSelected(true);
        }
    }//GEN-LAST:event_StaffsTableMouseClicked

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
        // TODO add your handling code here:
        Login log1=new Login();
        log1.show();
        dispose();
    }//GEN-LAST:event_Logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staffs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add1;
    private javax.swing.JTextField Age;
    private javax.swing.JLabel Delete1;
    private javax.swing.JRadioButton Female;
    private javax.swing.ButtonGroup Gender;
    private javax.swing.JLabel Home3;
    private javax.swing.JButton Logout1;
    private javax.swing.JRadioButton Male;
    private javax.swing.JRadioButton Others;
    private javax.swing.JTextField PhnNum1;
    private javax.swing.JTextField StAdd;
    private javax.swing.JTextField StName;
    private javax.swing.JTable StaffsTable;
    private javax.swing.JLabel Update1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables

    private void fetch() {

        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Dairymanagement","root","");
           String sql="select * from Staffs";
           Statement stmt=con.createStatement();
           ResultSet rs=stmt.executeQuery(sql);
           DefaultTableModel d1=(DefaultTableModel)StaffsTable.getModel();
           d1.setRowCount(0);
           while(rs.next())
           {
               Vector v2=new Vector();
                    v2.add(rs.getString("Id"));
                    v2.add(rs.getString("Name"));
                    v2.add(rs.getString("PhoneNumber"));
                    v2.add(rs.getString("Address"));
                    v2.add(rs.getString("Age"));
                    v2.add(rs.getString("Gender"));
               d1.addRow(v2);
           }
       }
       catch(Exception e)
       {
           System.out.println(e);
       }
    }

    private void clear() {
        StName.setText("");
        StName.setText("");
        PhnNum1.setText("");
        StAdd.setText("");
        Age.setText("");
        this.Gender.clearSelection();
}
}
